export const GET_USER_EMAIL = 'GET_USER_EMAIL';
export const GET_CURRENCIES = 'GET_CURRENCIES';
export const GET_CURRENCIES_SUCESS = 'GET_CURRENCIES_SUCESS';
export const GET_CURRENCIES_ERROR = 'GET_CURRENCIES_ERROR';
export const GET_RATES = 'GET_RATES';
export const GET_RATES_SUCESS = 'GET_RATES_SUCESS';
export const GET_RATES_ERROR = 'GET_RATES_ERROR';
export const REMOVE_ITEM = 'REMOVE_ITEM';
