export const CHANGE_USER_INFORMATION = 'CHANGE_USER_INFORMATION';
export const CHANGE_WALLET_INFORMATION = 'CHANGE_WALLET_INFORMATION';
export const GET_CURRENCIES = 'GET_CURRENCIES';
export const SET_CURRENCIES = 'SET_CURRENCIES';
export const REQUEST_CURRENCIES = 'REQUEST_CURRENCIES';
export const FAILED_REQUEST = 'FAILED_REQUEST';
