export const STORE_EMAIL = 'STORE_EMAIL';

export const REQUEST_CURRENCY = 'REQUEST_CURRENCY';

export const RECEIVE_CURRENCY = 'RECEIVE_CURRENCY';

export const REQUEST_EXPENSES = 'REQUEST_EXPENSES';

export const RECEIVE_EXPENSES = 'RECEIVE_EXPENSES';
