export const CHANGE_USER_INFORMATION = 'CHANGE_USER_INFORMATION';
export const CHANGE_WALLET_INFORMATION = 'CHANGE_WALLET_INFORMATION';
export const GET_CURRENCIES = 'GET_CURRENCIES';
export const GET_EXCHANGE_RATES = 'GET_EXCHANGE_RATES';
export const SET_EXPENSE = 'SET_EXPENSE';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
export const REQUEST_CURRENCIES = 'REQUEST_CURRENCIES';
export const FAILED_REQUEST = 'FAILED_REQUEST';
