export const VALIDATE_LOGIN = 'VALIDATE_LOGIN';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const GET_CURRENCIES = 'GET_CURRENCIES';
export const GET_CURRENCIES_SC = 'GET_CURRENCIES_SC';
export const GET_CURRENCIES_ER = 'GET_CURRENCIES_ER';
