export const LOGIN = 'LOGIN';
export const GET_CURRENCIES = 'GET_CURRENCIES';
export const GET_QUOTATIONS = 'GET_QUOTATIONS';

export const REQUEST_FAILED = 'REQUEST_FAILED';
export const REQUEST_FETCH = 'REQUEST_FETCH';
