export const LOGIN = 'LOGIN';
export const GET_CURRENCIES = 'GET_CURRENCIES';
export const GET_QUOTATIONS = 'GET_QUOTATIONS';
export const EXPENSE_REMOVE = 'EXPENSE_REMOVE';
export const EXPENSE_EDIT = 'EXPENSE_EDIT';
export const SAVE_EDITED_EXPENSE = 'SAVE_EDITED_EXPENSE';

export const REQUEST_FAILED = 'REQUEST_FAILED';
export const REQUEST_FETCH = 'REQUEST_FETCH';
